# Generated by Django 3.0.7 on 2020-11-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(default='Male', max_length=10)),
                ('age', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('exp_salary', models.IntegerField()),
                ('will_relocate', models.BooleanField(default=True)),
            ],
        ),
    ]
